name: Elemental CLI update

actions:
  pull-request:
    title: "updatecli: bump go version"
    kind: github/pullrequest
    scmid: ci
    spec:
      automerge: false
      upstream: true
      labels:
        - dependencies
        - kind/chore

scms:
  ci:
    kind: github
    spec:
      user: "Elemental CI [bot]"
      email: "elemental@suse.de"
      owner: "elemental-ci"
      repository: "elemental-cli"
      token: '{{ requiredEnv "ELEMENTAL_BOT_GITHUB_TOKEN" }}'
      username: 'elemental-ci-bot'
      branch: "main"

sources:
  goversion:
    name: Get Latest Go Release
    kind: githubrelease
    transformers:
        - trimprefix: go
    spec:
        owner: golang
        repository: go
        token: '{{ requiredEnv "ELEMENTAL_BOT_GITHUB_TOKEN" }}'
        username: 'elemental-ci-bot'
        versionfilter:
            kind: regex
            pattern: go1\.(\d*)\.(\d*)$

conditions:
  dockerTag:
      name: Is docker image golang:{{ source "goversion" }} published
      kind: dockerimage
      spec:
          image: golang
          tag: '{{ source "goversion" }}-alpine'
      sourceid: goversion

targets:
  githubActions:
    name: "Update Github Actions files with new go-version"
    kind: yaml
    sourceid: goversion
    scmid: ci
    spec:
      key: env.GO_VERSION
      files:
        - .github/workflows/build.yaml
        - .github/workflows/test.yaml
        - .github/workflows/docs.yaml
        - .github/workflows/lint.yaml
        - .github/workflows/release.yaml
  goDockerfile:
    name: "Update the value of ARG GO_VERSION in the Dockerfile"
    sourceid: goversion
    kind: dockerfile
    scmid: ci
    spec:
      file: Dockerfile
      instruction:
        keyword: "ARG"
        matcher: "GO_VERSION"
