---
name: Updatecli

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run once a day 
    - cron: '0 0 * * *'

jobs:
  updatecli:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with: 
          go-version-file: go.mod

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli in apply mode
        run: "updatecli apply --config .updatecli.yaml"
        env:
          ELEMENTAL_BOT_GITHUB_TOKEN: "${{ secrets.ELEMENTAL_BOT_GITHUB_TOKEN }}"
